# Import Libraries

In [7]:
import requests # for getting web contents
from bs4 import BeautifulSoup # for scraping web contents
import pandas as pd # for data analysis
import random  # used to choose random headers
import re  # used for regular expressions (regex)

# headers rotation

In [8]:
headers_list = [{ 
	'authority': 'transfermarkt.us', 
	'cache-control': 'max-age=0', 
	'sec-ch-ua': '"Chromium";v="91", " Not A;Brand";v="99", "Google Chrome";v="91"', 
	'sec-ch-ua-mobile': '?0', 
	'upgrade-insecure-requests': '1', 
	'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36', 
	'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 
	'sec-fetch-site': 'none', 
	'sec-fetch-mode': 'navigate', 
	'sec-fetch-user': '?1', 
	'sec-fetch-dest': 'document', 
	'accept-language': 'en-US,en;q=0.9',
},
                { 
	'authority': 'transfermarkt.us', 
	'cache-control': 'max-age=0', 
	'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 
	'sec-ch-ua-mobile': '?0', 
	'upgrade-insecure-requests': '1', 
	'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36', 
	'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 
	'sec-fetch-site': 'none', 
	'sec-fetch-mode': 'navigate', 
	'sec-fetch-user': '?1', 
	'sec-fetch-dest': 'document', 
	'accept-language': 'en-US,en;q=0.9',
}, 
                { 
	'authority': 'transfermarkt.us', 
	'cache-control': 'max-age=0', 
	'sec-ch-ua': '"Chromium";v="90", " Not A;Brand";v="99", "Google Chrome";v="90"', 
	'sec-ch-ua-mobile': '?0', 
	'upgrade-insecure-requests': '1', 
	'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36', 
	'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 
	'sec-fetch-site': 'none', 
	'sec-fetch-mode': 'navigate', 
	'sec-fetch-user': '?1', 
	'sec-fetch-dest': 'document', 
	'accept-language': 'en-US,en;q=0.9',
},
                { 
	'authority': 'transfermarkt.us', 
	'cache-control': 'max-age=0', 
	'sec-ch-ua-mobile': '?0', 
	'upgrade-insecure-requests': '1', 
	'user-agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148', 
	'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 
	'sec-fetch-site': 'none', 
	'sec-fetch-mode': 'navigate', 
	'sec-fetch-user': '?1', 
	'sec-fetch-dest': 'document', 
	'accept-language': 'en-US,en;q=0.9',
},
                { 
	'authority': 'transfermarkt.us', 
	'cache-control': 'max-age=0', 
	'sec-ch-ua': '"Chromium";v="89", " Not A;Brand";v="99", "Google Chrome";v="89"', 
	'sec-ch-ua-mobile': '?0', 
	'upgrade-insecure-requests': '1', 
	'user-agent': 'Mozilla/5.0 (Linux; Android 11; SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Mobile Safari/537.36', 
	'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 
	'sec-fetch-site': 'none', 
	'sec-fetch-mode': 'navigate', 
	'sec-fetch-user': '?1', 
	'sec-fetch-dest': 'document', 
	'accept-language': 'en-US,en;q=0.9',
}
]

# Récupération des données

In [26]:
headings = ['Rang', 'Joueur', 'Poste', 'Age', 'Nat.', 'Club', 'Valeur', 'Matchs', 'Buts', 'Buts_CSC', 'Passes_d', 
             'Cartons_jaunes', 'Second_avertissement', 'Cartons_rouges', 'Entre', 'Remplace', 'Buts_2021', 'Passes_2021', 'Minutes_2021', 
            'Buts_2022', 'Passes_2022', 'Minutes_2022', 'Buts_total', 'Passes_total', 'Minutes_total']

In [10]:
# getting the table body

# list to store all content
content = []

for i in range(1, 21):
    headers = random.choice(headers_list) 
    URL = f'https://www.transfermarkt.us/spieler-statistik/wertvollstespieler/marktwertetop?ajax=yw1&altersklasse=alle&ausrichtung=Sturm&jahrgang=0&kontinent_id=0&land_id=0&page={i}&plus=1&spielerposition_id=alle'

    # get web data
    page = requests.get(URL, headers=headers)
    # parse web data
    soup = BeautifulSoup(page.content, "html.parser")
    # getting the table body
    html_tbody = soup.find_all('tbody')[-1]
    #getting all the rows in table body
    html_text = [tr for tr in html_tbody.find_all('tr')]
    
    # loop through table body
    for tr in html_text:
        # getting all th, td
        th = tr.find_all(['th','td'])
        # storing all th value in row and removing white space
        row = [i.text.strip() for i in th]

        if len(row)==18:
            row.pop(1)
            row.pop(1)
            for year in [2021, 2022, 'ges']:
                str_url = tr.find(class_="rechts hauptlink").find('a')['href']    # get the url of the main page of the player
                URL_stats = 'https://www.transfermarkt.us'+str_url.replace('marktwertverlauf', 'leistungsdaten')+f'/plus/0?saison={str(year)}'  # get the url of the stats page
        
                headers_stats = random.choice(headers_list) 
                page_stats = requests.get(URL_stats, headers=headers_stats)
                soup_stats = BeautifulSoup(page_stats.content, "html.parser")
                html_tfoot = soup_stats.find_all('tfoot')[0]
                stats_data = html_tfoot.find_all(class_=["zentriert", "rechts"])
                stats_data_regex = [re.sub("<(?:\"[^\"]*\"['\"]*|'[^']*'['\"]*|[^'\">])+>", '', str(stats_data[i])) for i in range(len(stats_data))]
                
                buts, passes, minutes = [stats_data_regex[2], stats_data_regex[3], stats_data_regex[7]]
                
                row.append(buts)
                row.append(passes)
                row.append(minutes)

            content.append(row)

In [27]:
# save contents in a dataframe
data = pd.DataFrame(content[:], columns=headings)

# Mise en forme et analyse des données

In [28]:
# check few top rows of data
data.head()

,Rang,Joueur,Poste,Age,Nat.,Club,Valeur,Matchs,Buts,Buts_CSC,...,Remplace,Buts_2021,Passes_2021,Minutes_2021,Buts_2022,Passes_2022,Minutes_2022,Buts_total,Passes_total,Minutes_total
0,1,Erling Haaland,Centre-Forward,23,,,€180.00m,2,2,0,...,2,29,8,2.388',52,9,4.131',189,45,16.189'
1,2,Kylian Mbappé,Centre-Forward,24,,,€180.00m,0,0,0,...,0,39,26,3.903',41,10,3.564',244,116,24.452'
2,3,Vinicius Junior,Left Winger,23,,,€150.00m,1,0,0,...,1,22,20,4.272',23,21,4.759',73,69,18.064'
3,4,Bukayo Saka,Right Winger,21,,,€120.00m,2,1,0,...,0,12,7,3.353',15,11,3.744',61,58,17.186'
4,5,Victor Osimhen,Centre-Forward,24,,,€120.00m,0,0,0,...,0,18,6,2.310',31,5,3.021',97,24,13.467'

In [29]:
data = data.drop(columns=['Nat.', 'Club', 'Matchs', 'Buts', 'Buts_CSC', 'Passes_d', 
             'Cartons_jaunes', 'Second_avertissement', 'Cartons_rouges', 'Entre', 'Remplace'])

In [30]:
data.head()

,Rang,Joueur,Poste,Age,Valeur,Buts_2021,Passes_2021,Minutes_2021,Buts_2022,Passes_2022,Minutes_2022,Buts_total,Passes_total,Minutes_total
0,1,Erling Haaland,Centre-Forward,23,€180.00m,29,8,2.388',52,9,4.131',189,45,16.189'
1,2,Kylian Mbappé,Centre-Forward,24,€180.00m,39,26,3.903',41,10,3.564',244,116,24.452'
2,3,Vinicius Junior,Left Winger,23,€150.00m,22,20,4.272',23,21,4.759',73,69,18.064'
3,4,Bukayo Saka,Right Winger,21,€120.00m,12,7,3.353',15,11,3.744',61,58,17.186'
4,5,Victor Osimhen,Centre-Forward,24,€120.00m,18,6,2.310',31,5,3.021',97,24,13.467'

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rang           500 non-null    object
 1   Joueur         500 non-null    object
 2   Poste          500 non-null    object
 3   Age            500 non-null    object
 4   Valeur         500 non-null    object
 5   Buts_2021      500 non-null    object
 6   Passes_2021    500 non-null    object
 7   Minutes_2021   500 non-null    object
 8   Buts_2022      500 non-null    object
 9   Passes_2022    500 non-null    object
 10  Minutes_2022   500 non-null    object
 11  Buts_total     500 non-null    object
 12  Passes_total   500 non-null    object
 13  Minutes_total  500 non-null    object
dtypes: object(14)
memory usage: 54.8+ KB

In [32]:
# remove € symbol and m from Valeur and convert to float
# convert Age, Buts, Passes, and Minutes to int
# replace '-' values by 0
# translate the poste in french

data['Valeur'] = data['Valeur'].str.replace('€','')
data['Valeur'] = data['Valeur'].str.replace('m','')
data['Valeur'] = data['Valeur'].astype(float)
data['Age'] = data['Age'].astype(int)


data['Buts_2021'] = data['Buts_2021'].str.replace('-','0')
data['Buts_2022'] = data['Buts_2022'].str.replace('-','0')
data['Buts_total'] = data['Buts_total'].str.replace('-','0')
data['Passes_2021'] = data['Passes_2021'].str.replace('-','0')
data['Passes_2022'] = data['Passes_2022'].str.replace('-','0')
data['Passes_total'] = data['Passes_total'].str.replace('-','0')

data['Buts_2021'] = data['Buts_2021'].astype(int)
data['Buts_2022'] = data['Buts_2022'].astype(int)
data['Buts_total'] = data['Buts_total'].astype(int)

data['Passes_2021'] = data['Passes_2021'].astype(int)
data['Passes_2022'] = data['Passes_2022'].astype(int)
data['Passes_total'] = data['Passes_total'].astype(int)

data['Minutes_2021'] = data['Minutes_2021'].str.replace("'",'')
data['Minutes_2021'] = data['Minutes_2021'].str.replace(".",'')
data['Minutes_2021'] = data['Minutes_2021'].astype(int)

data['Minutes_2022'] = data['Minutes_2022'].str.replace("'",'')
data['Minutes_2022'] = data['Minutes_2022'].str.replace(".",'')
data['Minutes_2022'] = data['Minutes_2022'].astype(int)

data['Minutes_total'] = data['Minutes_total'].str.replace("'",'')
data['Minutes_total'] = data['Minutes_total'].str.replace(".",'')
data['Minutes_total'] = data['Minutes_total'].astype(int)

data['Poste'] = data['Poste'].str.replace('Centre-Forward', 'Avant-Centre')
data['Poste'] = data['Poste'].str.replace('Left Winger', 'Ailier Gauche')
data['Poste'] = data['Poste'].str.replace('Right Winger', 'Ailier Droit')
data['Poste'] = data['Poste'].str.replace('Second Striker', 'Deuxième Attaquant')

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rang           500 non-null    object
 1   Joueur         500 non-null    object
 2   Poste          500 non-null    object
 3   Age            500 non-null    int64
 4   Valeur         500 non-null    float64
 5   Buts_2021      500 non-null    int64
 6   Passes_2021    500 non-null    int64
 7   Minutes_2021   500 non-null    int64
 8   Buts_2022      500 non-null    int64
 9   Passes_2022    500 non-null    int64
 10  Minutes_2022   500 non-null    int64
 11  Buts_total     500 non-null    int64
 12  Passes_total   500 non-null    int64
 13  Minutes_total  500 non-null    int64
dtypes: float64(1), int64(10), object(3)
memory usage: 54.8+ KB

In [34]:
data.describe()

,Age,Valeur,Buts_2021,Passes_2021,Minutes_2021,Buts_2022,Passes_2022,Minutes_2022,Buts_total,Passes_total,Minutes_total
count,500.000000,500.00000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,24.984000,20.11700,10.532000,5.440000,2301.720000,10.252000,5.264000,2266.760000,75.840000,38.464000,16393.992000
std,3.561617,21.15007,7.877378,4.209732,971.872519,7.549735,3.923914,944.463656,71.270986,34.308408,10128.291757
min,17.000000,6.00000,0.000000,0.000000,7.000000,0.000000,0.000000,109.000000,2.000000,0.000000,632.000000
25%,22.000000,8.00000,5.000000,2.000000,1578.000000,5.000000,2.000000,1565.500000,35.000000,17.750000,9304.250000
50%,25.000000,13.00000,8.500000,5.000000,2309.500000,9.000000,5.000000,2254.500000,61.000000,30.000000,14748.000000
75%,27.000000,22.25000,14.000000,7.000000,2976.250000,14.000000,7.000000,2962.250000,93.250000,49.250000,21212.000000
max,38.000000,180.00000,50.000000,26.000000,5162.000000,52.000000,24.000000,4759.000000,721.000000,340.000000,79515.000000

In [35]:
data[data['Age']==38]

,Rang,Joueur,Poste,Age,Valeur,Buts_2021,Passes_2021,Minutes_2021,Buts_2022,Passes_2022,Minutes_2022,Buts_total,Passes_total,Minutes_total
226,227,Cristiano Ronaldo,Avant-Centre,38,15.0,24,3,3217,17,4,2752,721,225,79515

In [36]:
data[data['Buts_total']>500]

,Rang,Joueur,Poste,Age,Valeur,Buts_2021,Passes_2021,Minutes_2021,Buts_2022,Passes_2022,Minutes_2022,Buts_total,Passes_total,Minutes_total
62,63,Lionel Messi,Ailier Droit,36,35.0,11,15,2873,29,21,4021,718,340,72312
86,87,Robert Lewandowski,Avant-Centre,34,30.0,50,7,4006,33,8,3954,542,143,59712
226,227,Cristiano Ronaldo,Avant-Centre,38,15.0,24,3,3217,17,4,2752,721,225,79515

In [37]:
data['Joueur'].is_unique

False

In [38]:
# players having the same name
data[data['Joueur'].duplicated(keep=False)]

,Rang,Joueur,Poste,Age,Valeur,Buts_2021,Passes_2021,Minutes_2021,Buts_2022,Passes_2022,Minutes_2022,Buts_total,Passes_total,Minutes_total
130,131,Pedro,Avant-Centre,26,22.0,29,10,3214,27,4,2681,115,26,14139
319,320,Paulinho,Ailier Gauche,23,10.0,4,3,1633,17,6,3305,30,14,7494
429,430,Pedro,Ailier Gauche,17,7.0,3,0,301,2,0,491,5,0,792
475,476,Paulinho,Avant-Centre,30,6.5,14,8,3568,15,12,2502,137,57,28976

In [39]:
data.head(500)

,Rang,Joueur,Poste,Age,Valeur,Buts_2021,Passes_2021,Minutes_2021,Buts_2022,Passes_2022,Minutes_2022,Buts_total,Passes_total,Minutes_total
0,1,Erling Haaland,Avant-Centre,23,180.0,29,8,2388,52,9,4131,189,45,16189
1,2,Kylian Mbappé,Avant-Centre,24,180.0,39,26,3903,41,10,3564,244,116,24452
2,3,Vinicius Junior,Ailier Gauche,23,150.0,22,20,4272,23,21,4759,73,69,18064
3,4,Bukayo Saka,Ailier Droit,21,120.0,12,7,3353,15,11,3744,61,58,17186
4,5,Victor Osimhen,Avant-Centre,24,120.0,18,6,2310,31,5,3021,97,24,13467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Wilson Isidor,Avant-Centre,22,6.0,8,2,1478,10,5,1436,44,11,7925
496,497,Sorba Thomas,Ailier Droit,24,6.0,3,16,4123,0,8,2850,11,29,13030
497,498,Jacob Brown,Avant-Centre,25,6.0,14,5,3581,9,2,3070,42,24,16265
498,499,Casper Tengstedt,Avant-Centre,23,6.0,30,15,3158,0,1,511,73,31,9203
499,500,Mostafa Mohamed,Avant-Centre,25,6.0,8,5,1598,11,5,2952,70,20,14530

# Save Data into CSV

In [40]:
# save data
data.to_csv('data.csv', index=False)